### PR TITLE
NEWS format expected by pkgdown

### PR DESCRIPTION
**Pull request by maelle**
cf https://github.com/r-lib/pkgdown/issues/1947

### CODE REVIEW

**Comment by richfitz** [comment]
Thanks - I need to sort this for cyphr too I believe

**Comment by maelle** [comment]
Too bad I had already made the cyphr PR! :joy:

**Comment by richfitz** [comment]
I've merged this PR into #55, so it should merge in there

**Comment by maelle** [comment]
Also note that if all goes well in future versions of pkgdown it'll be possible again to use h2 as section headers in NEWS.md. These PRs are workarounds.

**Pull request merged**
